# Generated by Django 4.2.9 on 2024-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
